---
title: "Econ 1042 PS1"
author: "Owen Asnis"
date: "2023-02-01"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(estimatr)
library(robustbase)

```

# Data Wrangling 

```{r data wrangling}

kickers <- read_csv("kickers_v2.csv",
                    show_col_types = FALSE) %>%
  rename(., "ID" = "...1") %>%
  mutate(Grass = if_else(Grass == TRUE, 1, 0))

```

# Question 1

```{r Q1}

min(kickers$Distance)
max(kickers$Distance)
mean(kickers$Distance)
median(kickers$Distance)

kickers %>% 
  filter(Distance == max(Distance))

```

# Question 2

```{r Q2}

forty_to_fortyfive <- kickers %>%
  filter(Distance %in% (40:45))

mean(forty_to_fortyfive$Success) * 100

over_fortyfive <- kickers %>% 
  filter(Distance > 45)

mean(over_fortyfive$Success) * 100

```

# Question 3

```{r Q3}

grass_only <- kickers %>% 
  filter(Grass == 1)

mean(grass_only$Success) * 100

turf_only <- kickers %>% 
  filter(Grass == 0)

mean(turf_only$Success) * 100

lm1 <- lm_robust(Success ~ Grass, data = kickers)
summary(lm1)

```

# Question 4 

```{r Q4}

cor(kickers$Distance, kickers$Grass)
cor(kickers$Distance, kickers$Success)

```

# Question 5 

```{r Q5}

# short-form(coefficient) = long-form(coefficient) + (omitted variable coefficient)(correlation)

lm2 <- lm_robust(Success ~ Grass + Distance, data = kickers)
summary(lm2)

# becomes more negative (adding distance is omitted variable bias)

```

# Question 6

```{r Q6}

lm3 <- lm_robust(Success ~ Distance + Grass + ScoreDiff + GameMinute, 
                 data = kickers)
summary(lm3)

lm4 <- lm_robust(Success ~ Distance + Grass + ScoreDiff + GameMinute + Kicker, 
                 data = kickers)
summary(lm4)

# Accounts for the skill of the kicker 

```

# Question 7 

```{r Q7}

new_data <- kickers %>%
  filter(Kicker == "Tucker", 
         ScoreDiff == -11, 
         Year == 2015, 
         GameMinute == 30)

predict(lm4, newdata = new_data) * 100

# estimate - Tucker coefficient 

```
